language: python
sudo: false
cache: pip
matrix:
  include:
    - python: 3.6
      env: TOXENV=isort
    - python: 2.7
      env: TOXENV=py27-django-1.8
    - python: 2.7
      env: TOXENV=py27-django-1.10
    - python: 2.7
      env: TOXENV=py27-django-1.11
    - python: 3.3
      env: TOXENV=py33-django-1.8
    - python: 3.4
      env: TOXENV=py34-django-1.8
    - python: 3.4
      env: TOXENV=py34-django-1.10
    - python: 3.4
      env: TOXENV=py34-django-1.11
    - python: 3.5
      env: TOXENV=py35-django-1.10
    - python: 3.5
      env: TOXENV=py35-django-1.11
    - python: 3.5
      env: TOXENV=py35-master
    - python: 3.6
      env: TOXENV=py36-django-1.11
    - python: 3.6
      env: TOXENV=py36-master
  allow_failures:
    - python: 3.5
      env: TOXENV=py35-master
    - python: 3.6
      env: TOXENV=py36-master
install:
  - pip install coverage tox
script:
  - tox
after_success:
  - coveralls
